import {
  Utensils,
  UtensilsCrossed,
  ChefHat,
  Home,
  Zap,
  CreditCard,
  Wallet,
  Calendar,
  CalendarDays,
  ShoppingCart,
  ShoppingBag,
  Bell,
  Package,
  User,
  LogOut,
  Menu,
  Table,
  Plus,
  Trash2,
  Armchair,
  TableProperties,
  LayoutDashboard,
  History,
  Check,
  ClipboardList,
  IndianRupee,
  TrendingUp,
  BarChart3,
  CircleDot,
  AlertCircle,
  Power,
  Pause,
  Play,
  Clock,
  AlertTriangle,
  ChevronLeft,
  ChevronRight,
  Eye,
  EyeOff,
  Loader2,
  CheckCircle2,
  Circle,
  Ban,
  Search,
  FolderOpen,
  X,
  CircleX,
  Star,
  Moon,
  Sun,
  Edit,
  Key,
} from "lucide-react";

export const Icons = {
  utensils: Utensils,
  utensilsCrossed: UtensilsCrossed,
  chef: ChefHat,
  home: Home,
  zap: Zap,
  card: CreditCard,
  payment: CreditCard,
  wallet: Wallet,
  calendar: Calendar,
  calendarDays: CalendarDays,
  cart: ShoppingCart,
  shoppingBag: ShoppingBag,
  bell: Bell,
  package: Package,
  user: User,
  logout: LogOut,
  menu: Menu,
  table: Table,
  plus: Plus,
  trash: Trash2,
  armchair: Armchair,
  tableProperties: TableProperties,
  dashboard: LayoutDashboard,
  historyIcon: History,
  check: Check,
  clipboard: ClipboardList,
  rupee: IndianRupee,
  trendingUp: TrendingUp,
  chart: BarChart3,
  dot: CircleDot,
  alertCircle: AlertCircle,
  power: Power,
  pause: Pause,
  play: Play,
  clock: Clock,
  warning: AlertTriangle,
  left: ChevronLeft,
  right: ChevronRight,
  eye: Eye,
  eyeOff: EyeOff,
  loader: Loader2,
  checkCircle: CheckCircle2,
  circle: Circle,
  ban: Ban,
  search: Search,
  folderOpen: FolderOpen,
  close: X,
  error: CircleX,
  star: Star,
  moon: Moon,
  sun: Sun,
  edit: Edit,
  key: Key,
};
